name: Manual Trigger to Discord

on:
  workflow_dispatch:

jobs:
  notify-discord-manual:
    runs-on: ubuntu-latest
    steps:
      - name: Actions for Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@0.4.0
        with:
          args: |
            ✅ **Triggered Workflow**
            • Repo: ${{ github.repository }}
            • Branch: ${{ github.ref_name }}
            • Triggered by: ${{ github.actor }}
